In [8]:
import sys
from pathlib import Path
from dotenv import dotenv_values
import pandas as pd

# Load environment variables from the .env file
env_vars = dotenv_values()  # Load variables from the .env file

# Get the workspace path from the environment variables
WORKSPACE_PATH = Path(
    env_vars.get("WORKSPACE_PATH", "")
)  # Fetch WORKSPACE_PATH from .env

if not WORKSPACE_PATH:
    raise ValueError("WORKSPACE_PATH is not defined in the .env file or is empty.")

# Add the WORKSPACE_PATH folder to the Python path
sys.path.append(str(WORKSPACE_PATH))

# Import custom utility functions
from src.config.utils import read_csv, split_string, aggregate_vertical, write_excel

DATA_DIR = Path(env_vars["DATA_DIR"])
RESULTS_DIR = Path(env_vars["RESULTS_DIR"])
MOMENT_OF_SUICIDE_FEATURES = split_string(env_vars["MOMENT_OF_SUICIDE_FEATURES"])
SOCIO_DEMOGRAPHIC_FEATURES = split_string(env_vars["SOCIO_DEMOGRAPHIC_FEATURES"])

In [9]:
# Read CSV File
csv_file_path = DATA_DIR / "processed" / "encoded_data.csv"
df_encoded = read_csv(csv_file_path)
csv_file_path = DATA_DIR / "processed" / "group_set.csv"
df_groups = read_csv(csv_file_path)

c:\Users\huber\OneDrive\Dokumenty\GitHub\ippan_suicide_study\src\config\utils.py:139: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(file_path, **kwargs)

In [10]:
FEATURES = list(set(SOCIO_DEMOGRAPHIC_FEATURES + MOMENT_OF_SUICIDE_FEATURES))
columns_to_aggregate = [
    column
    for column in df_encoded.columns
    if any(column.startswith(feature) for feature in FEATURES)
]
group_columns = [column for column in df_groups.columns if column.startswith("Group")]

In [11]:
df = df_encoded.merge(df_groups[["ID"] + group_columns], on="ID", how="left")

In [12]:
df = df[group_columns + columns_to_aggregate]

In [13]:
# Apply the function
count_result = aggregate_vertical(
    df,
    index_columns=["Group_A", "Group_AF", "Group_AG", "Group_AGF"],
    header="Count",
    agg_func="count",
)
count_result

                     Count
Column
Group_A   35_64      58397
          19_34      37052
          65         13794
          00_18       9599
Group_AF  35_64_1    31067
          35_64_0    27330
          19_34_0    23924
          19_34_1    13128
          65_1       10587
          00_18_0     8335
          65_0        3207
          00_18_1     1264
Group_AG  35_64_M    46131
          19_34_M    27889
          35_64_F    12266
          65_M       10401
          19_34_F     9163
          00_18_F     6435
          65_F        3393
          00_18_M     3164
Group_AGF 35_64_M_1  26866
          35_64_M_0  19265
          19_34_M_0  16260
          19_34_M_1  11629
          65_M_1      8415
          35_64_F_0   8065
          19_34_F_0   7664
          00_18_F_0   6018
          35_64_F_1   4201
          00_18_M_0   2317
          65_F_1      2172
          65_M_0      1986
          19_34_F_1   1499
          65_F_0      1221
          00_18_M_1    847
          00_18_F_1    417

In [14]:
write_excel(
    file_path=RESULTS_DIR / "group_exploration.xlsx",
    data=count_result,
    sheet_name="count_result",
    mode="w",
    index=True,
)

In [15]:
# Apply the function
feature_result = aggregate_vertical(
    df,
    index_columns=["Group_A", "Group_AF", "Group_AG", "Group_AGF"],
    target_columns=columns_to_aggregate,
    header="Count",
    agg_func="sum",
)
feature_result

                     Gender  Marital_Cohabitant  Marital_Cohabiting  \
Column
Group_A   00_18        3164                   9                   2
          19_34       27889                2403                 145
          35_64       46131                3326                 248
          65          10401                 212                  13
Group_AF  00_18_0      2317                   9                   2
          00_18_1       847                   0                   0
          19_34_0     16260                1647                 116
          19_34_1     11629                 756                  29
          35_64_0     19265                1969                 170
          35_64_1     26866                1357                  78
          65_0         1986                  58                   6
          65_1         8415                 154                   7
Group_AG  00_18_F         0                   4                   2
          00_18_M      3164                   5                   0
          19_34_F         0                 703                  73
          19_34_M     27889                1700                  72
          35_64_F         0                 941                  82
          35_64_M     46131                2385                 166
          65_F            0                  31                   3
          65_M        10401                 181                  10
Group_AGF 00_18_F_0       0                   4                   2
          00_18_F_1       0                   0                   0
          00_18_M_0    2317                   5                   0
          00_18_M_1     847                   0                   0
          19_34_F_0       0                 596                  66
          19_34_F_1       0                 107                   7
          19_34_M_0   16260                1051                  50
          19_34_M_1   11629                 649                  22
          35_64_F_0       0                 744                  70
          35_64_F_1       0                 197                  12
          35_64_M_0   19265                1225                 100
          35_64_M_1   26866                1160                  66
          65_F_0          0                  15                   2
          65_F_1          0                  16                   1
          65_M_0       1986                  43                   4
          65_M_1       8415                 138                   6

                     Marital_Divorced  Marital_Married  Marital_Separated  \
Column
Group_A   00_18                     3               12                  0
          19_34                  1048             5897                 69
          35_64                  7551            30578                453
          65                      885             7407                 47
Group_AF  00_18_0                   0                9                  0
          00_18_1                   3                3                  0
          19_34_0                 654             3828                 39
          19_34_1                 394             2069                 30
          35_64_0                3304            13984                183
          35_64_1                4247            16594                270
          65_0                    201             1731                  9
          65_1                    684             5676                 38
Group_AG  00_18_F                   0                8                  0
          00_18_M                   3                4                  0
          19_34_F                 318             1664                 19
          19_34_M                 730             4233                 50
          35_64_F                1617             6876                 75
          35_64_M                5934            23702                378
          65_F                    194             1187                  5
          65_M                    691             6220                 42
Group_AGF 00_18_F_0                 0                5                  0
          00_18_F_1                 0                3                  0
          00_18_M_0                 0                4                  0
          00_18_M_1                 3                0                  0
          19_34_F_0               251             1357                 11
          19_34_F_1                67              307                  8
          19_34_M_0               403             2471                 28
          19_34_M_1               327             1762                 22
          35_64_F_0              1081             4365                 49
          35_64_F_1               536             2511                 26
          35_64_M_0              2223             9619                134
          35_64_M_1              3711            14083                244
          65_F_0                   81              452                  2
          65_F_1                  113              735                  3
          65_M_0                  120             1279                  7
          65_M_1                  571             4941                 35

                     Marital_Single  Marital_Widowed  Education_Higher  \
Column
Group_A   00_18                9573                0                 0
          19_34               27435               55              2976
          35_64               14208             2033              6649
          65                    966             4264              1226
Group_AF  00_18_0              8315                0                 0
          00_18_1              1258                0                 0
          19_34_0             17599               41              1906
          19_34_1              9836               14              1070
          35_64_0              6819              901              3359
          35_64_1              7389             1132              3290
          65_0                  183             1019               334
          65_1                  783             3245               892
Group_AG  00_18_F              6421                0                 0
          00_18_M              3152                0                 0
          19_34_F              6348               38              1283
          19_34_M             21087               17              1693
          35_64_F              1713              962              2619
          35_64_M             12495             1071              4030
          65_F                  134             1839               440
          65_M                  832             2425               786
Group_AGF 00_18_F_0            6007                0                 0
          00_18_F_1             414                0                 0
          00_18_M_0            2308                0                 0
          00_18_M_1             844                0                 0
          19_34_F_0            5351               32              1025
          19_34_F_1             997                6               258
          19_34_M_0           12248                9               881
          19_34_M_1            8839                8               812
          35_64_F_0            1195              561              1691
          35_64_F_1             518              401               928
          35_64_M_0            5624              340              1668
          35_64_M_1            6871              731              2362
          65_F_0                 45              624               169
          65_F_1                 89             1215               271
          65_M_0                138              395               165
          65_M_1                694             2030               621

                     Education_LowerSecondary  ...  Context_Other  \
Column                                         ...
Group_A   00_18                           149  ...           1090
          19_34                           328  ...           5331
          35_64                            73  ...          10232
          65                               11  ...           1895
Group_AF  00_18_0                         132  ...            918
          00_18_1                          17  ...            172
          19_34_0                         223  ...           3174
          19_34_1                         105  ...           2157
          35_64_0                          38  ...           4151
          35_64_1                          35  ...           6081
          65_0                              2  ...            416
          65_1                              9  ...           1479
Group_AG  00_18_F                          96  ...            684
          00_18_M                          53  ...            406
          19_34_F                          76  ...           1108
          19_34_M                         252  ...           4223
          35_64_F                          13  ...           1668
          35_64_M                          60  ...           8564
          65_F                              0  ...            387
          65_M                             11  ...           1508
Group_AGF 00_18_F_0                        91  ...            638
          00_18_F_1                         5  ...             46
          00_18_M_0                        41  ...            280
          00_18_M_1                        12  ...            126
          19_34_F_0                        72  ...            915
          19_34_F_1                         4  ...            193
          19_34_M_0                       151  ...           2259
          19_34_M_1                       101  ...           1964
          35_64_F_0                         9  ...           1116
          35_64_F_1                         4  ...            552
          35_64_M_0                        29  ...           3035
          35_64_M_1                        31  ...           5529
          65_F_0                            0  ...            141
          65_F_1                            0  ...            246
          65_M_0                            2  ...            275
          65_M_1                            9  ...           1233

                     Context_FamilyConflict  Context_SchoolWork  \
Column
Group_A   00_18                        1411                1069
          19_34                        5936                 899
          35_64                       10511                 875
          65                            816                  36
Group_AF  00_18_0                      1238                 935
          00_18_1                       173                 134
          19_34_0                      4012                 664
          19_34_1                      1924                 235
          35_64_0                      5867                 510
          35_64_1                      4644                 365
          65_0                          358                  19
          65_1                          458                  17
Group_AG  00_18_F                       943                 724
          00_18_M                       468                 345
          19_34_F                      1199                 324
          19_34_M                      4737                 575
          35_64_F                      1746                 200
          35_64_M                      8765                 675
          65_F                          155                  11
          65_M                          661                  25
Group_AGF 00_18_F_0                     892                 676
          00_18_F_1                      51                  48
          00_18_M_0                     346                 259
          00_18_M_1                     122                  86
          19_34_F_0                    1062                 284
          19_34_F_1                     137                  40
          19_34_M_0                    2950                 380
          19_34_M_1                    1787                 195
          35_64_F_0                    1411                 165
          35_64_F_1                     335                  35
          35_64_M_0                    4456                 345
          35_64_M_1                    4309                 330
          65_F_0                        105                   8
          65_F_1                         50                   3
          65_M_0                        253                  11
          65_M_1                        408                  14

                     Context_MentalHealth  Context_HealthLoss  \
Column
Group_A   00_18                      4177                  48
          19_34                     12914                 617
          35_64                     21198                3753
          65                         5076                4460
Group_AF  00_18_0                    3696                  42
          00_18_1                     481                   6
          19_34_0                    8349                 323
          19_34_1                    4565                 294
          35_64_0                    9777                1138
          35_64_1                   11421                2615
          65_0                       1310                 696
          65_1                       3766                3764
Group_AG  00_18_F                    3066                  29
          00_18_M                    1111                  19
          19_34_F                    4090                 170
          19_34_M                    8824                 447
          35_64_F                    6000                 779
          35_64_M                   15198                2974
          65_F                       1870                 681
          65_M                       3206                3779
Group_AGF 00_18_F_0                  2861                  28
          00_18_F_1                   205                   1
          00_18_M_0                   835                  14
          00_18_M_1                   276                   5
          19_34_F_0                  3347                 114
          19_34_F_1                   743                  56
          19_34_M_0                  5002                 209
          19_34_M_1                  3822                 238
          35_64_F_0                  3634                 371
          35_64_F_1                  2366                 408
          35_64_M_0                  6143                 767
          35_64_M_1                  9055                2207
          65_F_0                      635                 207
          65_F_1                     1235                 474
          65_M_0                      675                 489
          65_M_1                     2531                3290

                     Context_HeartBreak  Context_CloseDeath  Context_Finances  \
Column
Group_A   00_18                    1729                 144                21
          19_34                    8824                 694              1857
          35_64                    4992                1581              4991
          65                        140                 670               513
Group_AF  00_18_0                  1448                 131                13
          00_18_1                   281                  13                 8
          19_34_0                  5944                 487              1107
          19_34_1                  2880                 207               750
          35_64_0                  3097                 841              2020
          35_64_1                  1895                 740              2971
          65_0                       65                 174               140
          65_1                       75                 496               373
Group_AG  00_18_F                   968                  97                 5
          00_18_M                   761                  47                16
          19_34_F                  1858                 241               236
          19_34_M                  6966                 453              1621
          35_64_F                   805                 457               690
          35_64_M                  4187                1124              4301
          65_F                       24                 144               112
          65_M                      116                 526               401
Group_AGF 00_18_F_0                 901                  95                 5
          00_18_F_1                  67                   2                 0
          00_18_M_0                 547                  36                 8
          00_18_M_1                 214                  11                 8
          19_34_F_0                1611                 193               202
          19_34_F_1                 247                  48                34
          19_34_M_0                4333                 294               905
          19_34_M_1                2633                 159               716
          35_64_F_0                 681                 329               434
          35_64_F_1                 124                 128               256
          35_64_M_0                2416                 512              1586
          35_64_M_1                1771                 612              2715
          65_F_0                     17                  58                47
          65_F_1                      7                  86                65
          65_M_0                     48                 116                93
          65_M_1                     68                 410               308

                     Context_Crime  Context_Disability
Column
Group_A   00_18                 20                  13
          19_34                269                  72
          35_64                500                 309
          65                    36                 242
Group_AF  00_18_0               18                  10
          00_18_1                2                   3
          19_34_0              126                  41
          19_34_1              143                  31
          35_64_0              178                 114
          35_64_1              322                 195
          65_0                   4                  54
          65_1                  32                 188
Group_AG  00_18_F                5                   2
          00_18_M               15                  11
          19_34_F               19                  18
          19_34_M              250                  54
          35_64_F               24                  33
          35_64_M              476                 276
          65_F                   1                  39
          65_M                  35                 203
Group_AGF 00_18_F_0              5                   2
          00_18_F_1              0                   0
          00_18_M_0             13                   8
          00_18_M_1              2                   3
          19_34_F_0             17                  15
          19_34_F_1              2                   3
          19_34_M_0            109                  26
          19_34_M_1            141                  28
          35_64_F_0             16                  15
          35_64_F_1              8                  18
          35_64_M_0            162                  99
          35_64_M_1            314                 177
          65_F_0                 0                  15
          65_F_1                 1                  24
          65_M_0                 4                  39

In [16]:
write_excel(
    file_path=RESULTS_DIR / "group_exploration.xlsx",
    data=feature_result,
    sheet_name="feature_result",
    mode="a",
    index=True,
)