In [18]:
import sys
from pathlib import Path
from dotenv import dotenv_values
import pandas as pd

# Load environment variables from the .env file
env_vars = dotenv_values()  # Load variables from the .env file

# Get the workspace path from the environment variables
WORKSPACE_PATH = Path(
    env_vars.get("WORKSPACE_PATH", "")
)  # Fetch WORKSPACE_PATH from .env

if not WORKSPACE_PATH:
    raise ValueError("WORKSPACE_PATH is not defined in the .env file or is empty.")

# Add the WORKSPACE_PATH folder to the Python path
sys.path.append(str(WORKSPACE_PATH))

# Import custom utility functions
from src.config.utils import (
    read_csv,
    split_string,
    left_join_excel_sheets,
    aggregate_count,
    aggregate_sum,
    write_excel,
)

DATA_DIR = Path(env_vars["DATA_DIR"])
RESULTS_DIR = Path(env_vars["RESULTS_DIR"])
MOMENT_OF_SUICIDE_FEATURES = split_string(env_vars["MOMENT_OF_SUICIDE_FEATURES"])
SOCIO_DEMOGRAPHIC_FEATURES = split_string(env_vars["SOCIO_DEMOGRAPHIC_FEATURES"])

In [19]:
# Read encoded data
csv_file_path = DATA_DIR / "processed" / "encoded_data.csv"
df_encoded = read_csv(csv_file_path)

In [20]:
# Read LCA classes
excel_file_path = DATA_DIR / "processed" / "lca_group_results.xlsx"
df_lca_classes = left_join_excel_sheets(excel_file_path, base_df=None, on="ID")

In [21]:
# Read group set
csv_file_path = DATA_DIR / "processed" / "group_set.csv"
df_groups = read_csv(csv_file_path)

In [22]:
FEATURES = list(set(SOCIO_DEMOGRAPHIC_FEATURES + MOMENT_OF_SUICIDE_FEATURES))
columns_to_aggregate = [
    column
    for column in df_encoded.columns
    if any(column.startswith(feature) for feature in FEATURES)
]
class_columns = [
    column for column in df_lca_classes.columns if column.endswith("_class")
]
group_columns = [column for column in df_groups.columns if column.startswith("Group")]

In [23]:
df = df_encoded.merge(df_lca_classes[["ID"] + class_columns], on="ID", how="left")

In [24]:
df = df.merge(df_groups[["ID"] + group_columns], on="ID", how="left")

In [25]:
df = df[["DateY"] + class_columns + columns_to_aggregate + group_columns]

In [26]:
df["DateY"] = df["DateY"].astype(int)

In [27]:
df.columns

Index(['DateY', 'LCA_Group_AF_class', 'LCA_Group_AG_class',
       'LCA_Group_AGF_class', 'Gender', 'Marital_Cohabitant',
       'Marital_Cohabiting', 'Marital_Divorced', 'Marital_Married',
       'Marital_Separated', 'Marital_Single', 'Marital_Widowed',
       'Education_Higher', 'Education_LowerSecondary', 'Education_PrePrimary',
       'Education_Primary', 'Education_Secondary', 'Education_Vocational',
       'WorkInfo_Agriculturalist', 'WorkInfo_Employed', 'WorkInfo_Student',
       'WorkInfo_Unemployed', 'Income_Benefits', 'Income_Dependent',
       'Income_NoSteady', 'Income_Steady', 'Fatal', 'Place_Forest',
       'Place_House', 'Place_Institution', 'Place_Isolation', 'Place_Other',
       'Place_PoliceArmy', 'Place_Railway', 'Place_Road', 'Place_School',
       'Place_UtilitySpaces', 'Place_WaterRes', 'Place_Work',
       'Method_Drowning', 'Method_Drugs', 'Method_Gas', 'Method_Hanging',
       'Method_Jumping', 'Method_Other', 'Method_Poisoning',
       'Method_Schooting', 'Method_SelfHarm', 'Method_Shooting',
       'Method_Vehicle', 'Substance_Alco', 'Substance_AlcoOtherSub',
       'Substance_OtherSub', 'Substance_Sober', 'AbuseInfo_Alco',
       'AbuseInfo_AlcoOtherSub', 'AbuseInfo_Not', 'AbuseInfo_OtherSub',
       'Context_Other', 'Context_FamilyConflict', 'Context_SchoolWork',
       'Context_MentalHealth', 'Context_HealthLoss', 'Context_HeartBreak',
       'Context_CloseDeath', 'Context_Finances', 'Context_Crime',
       'Context_Disability', 'Group_A', 'Group_AG', 'Group_AF', 'Group_AGF'],
      dtype='object')

# Class Count Group_AG

In [29]:
# Apply the function
count_result = aggregate_count(
    df,
    group_columns=["Group_AG"],
    value_columns=["LCA_Group_AG_class"],
    header="Count",
)
count_result

                       1      2      3     4     5
Column   Group_AG
Group_AG 00_18_F    2101   2021   1715   991   533
         00_18_M    1436    848    528   428   176
         19_34_F    3086   2655   1872  1852   619
         19_34_M   11195   6397   5650  3915  2241
         35_64_F    4015   3538   3186  1777   719
         35_64_M   13517  12680  10414  7319  4982
         65_F       1733   1010    720   106    43
         65_M       3812   2518   1940  1736  1010

In [35]:
write_excel(
    file_path=RESULTS_DIR / "lca_class_exploration.xlsx",
    data=count_result,
    sheet_name="count_result",
    mode="w",
    index=True,
)

## 00_18_F

In [30]:
df_exploration = df[df["Group_AG"] == "00_18_F"]

In [31]:
# Apply the function
feature_result = aggregate_sum(
    df_exploration,
    group_columns=["LCA_Group_AG_class"],
    value_columns=columns_to_aggregate,
)
feature_result

                                       Gender  Marital_Cohabitant  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                        0                   0
                   2                        0                   0
                   3                        0                   0
                   4                        0                   4
                   5                        0                   0

                                       Marital_Cohabiting  Marital_Divorced  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                                    0                 0
                   2                                    0                 0
                   3                                    0                 0
                   4                                    2                 0
                   5                                    0                 0

                                       Marital_Married  Marital_Separated  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                                 0                  0
                   2                                 0                  0
                   3                                 0                  0
                   4                                 4                  0
                   5                                 4                  0

                                       Marital_Single  Marital_Widowed  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                             2101                0
                   2                             2021                0
                   3                             1715                0
                   4                              981                0
                   5                              529                0

                                       Education_Higher  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                                  0
                   2                                  0
                   3                                  0
                   4                                  0
                   5                                  0

                                       Education_LowerSecondary  ...  \
Column             LCA_Group_AG_class                            ...
LCA_Group_AG_class 1                                         61  ...
                   2                                         42  ...
                   3                                         37  ...
                   4                                         25  ...
                   5                                         14  ...

                                       Context_Other  Context_FamilyConflict  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                             246                     345
                   2                             177                     251
                   3                             204                     246
                   4                              88                     179
                   5                              62                      64

                                       Context_SchoolWork  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                                  255
                   2                                  267
                   3                                  197
                   4                                   95
                   5                                   53

                                       Context_MentalHealth  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                                    983
                   2                                   1035
                   3                                    769
                   4                                    445
                   5                                    270

                                       Context_HealthLoss  Context_HeartBreak  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                                   10                 273
                   2                                   13                 283
                   3                                    8                 283
                   4                                    3                 178
                   5                                    3                  77

                                       Context_CloseDeath  Context_Finances  \
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                                   26                 2
                   2                                   34                 4
                   3                                   33                 1
                   4                                   13                 1
                   5                                    7                 1

                                       Context_Crime  Context_Disability
Column             LCA_Group_AG_class
LCA_Group_AG_class 1                               2                   0
                   2                               1                   0
                   3                               2                   0
                   4                               2                   2
                   5                               0                   0

[5 rows x 64 columns]

In [37]:
write_excel(
    file_path=RESULTS_DIR / "lca_class_exploration.xlsx",
    data=feature_result,
    sheet_name="feature_result",
    mode="a",
    index=True,
)

## 19_34_M

# Feature percentage

In [38]:
# Ensure the indices of both DataFrames match
if not feature_result.index.equals(count_result.index):
    raise ValueError("Indices of feature_result and count_result do not match.")

# Divide each column in feature_result by the "Count" column in count_result
percentage_feature_result = (
    feature_result.div(count_result["Count"], axis=0).mul(100).round(1)
)

percentage_feature_result

                       Gender  Marital_Cohabitant  Marital_Cohabiting  \
Column
LCA_Group_AF_class  1    70.3                 4.9                 0.6
                    2    71.1                 5.5                 0.7
                    3    78.3                 6.2                 0.7
                    4    71.7                 2.3                 0.4
                    5    79.8                 2.9                 0.3
LCA_Group_AG_class  1    73.3                 5.0                 0.6
                    2    70.9                 5.1                 0.8
                    3    71.2                 4.4                 0.5
                    4    73.9                 3.5                 0.4
                    5    81.5                 5.9                 0.7
LCA_Group_AGF_class 1    71.3                 4.4                 0.6
                    2    70.9                 4.5                 0.6
                    3    73.7                 7.0                 0.7
                    4    78.3                 3.5                 0.5
                    5    76.3                 4.2                 0.5

                       Marital_Divorced  Marital_Married  Marital_Separated  \
Column
LCA_Group_AF_class  1               8.7             32.4                0.4
                    2               8.9             29.4                0.5
                    3               9.1             40.1                0.6
                    4               4.1             48.8                0.2
                    5               6.2             46.3                0.5
LCA_Group_AG_class  1               7.7             37.3                0.4
                    2               8.2             33.4                0.5
                    3               7.6             39.9                0.4
                    4               8.5             32.1                0.5
                    5               8.6             41.6                0.6
LCA_Group_AGF_class 1               6.2             40.5                0.4
                    2               8.5             32.6                0.4
                    3              10.5             37.6                0.6
                    4               7.2             33.9                0.5
                    5               9.1             34.3                0.5

                       Marital_Single  Marital_Widowed  Education_Higher  \
Column
LCA_Group_AF_class  1            47.4              5.6               8.3
                    2            49.2              5.7               9.8
                    3            38.3              5.0               9.2
                    4            38.9              5.3              12.0
                    5            40.3              3.5               7.2
LCA_Group_AG_class  1            43.2              5.7               9.5
                    2            45.5              6.5              10.0
                    3            42.8              4.4               8.7
                    4            50.2              4.8               8.9
                    5            39.9              2.6               7.5
LCA_Group_AGF_class 1            42.9              5.0               9.2
                    2            46.4              7.0               9.7
                    3            38.0              5.6               9.0
                    4            51.3              3.1               8.4
                    5            47.6              3.9               9.7

                       Education_LowerSecondary  ...  Context_Other  \
Column                                           ...
LCA_Group_AF_class  1                       0.7  ...           14.8
                    2                       0.6  ...           13.8
                    3                       0.5  ...           16.6
                    4                       0.6  ...           14.9
                    5                       0.5  ...           19.3
LCA_Group_AG_class  1                       0.7  ...           15.9
                    2                       0.6  ...           13.8
                    3                       0.7  ...           15.6
                    4                       0.6  ...           15.1
                    5                       0.3  ...           17.1
LCA_Group_AGF_class 1                       0.6  ...           16.0
                    2                       0.8  ...           14.3
                    3                       0.5  ...           18.2
                    4                       0.6  ...           15.1
                    5                       0.5  ...           10.4

                       Context_FamilyConflict  Context_SchoolWork  \
Column
LCA_Group_AF_class  1                    14.1                 2.7
                    2                    14.7                 2.9
                    3                    19.7                 2.0
                    4                    14.8                 2.4
                    5                    18.2                 2.4
LCA_Group_AG_class  1                    15.6                 2.5
                    2                    15.4                 2.6
                    3                    16.5                 2.8
                    4                    12.9                 2.3
                    5                    20.1                 2.2
LCA_Group_AGF_class 1                    17.9                 2.9
                    2                    13.8                 3.0
                    3                    18.0                 2.0
                    4                    15.5                 2.5
                    5                     9.5                 1.2

                       Context_MentalHealth  Context_HealthLoss  \
Column
LCA_Group_AF_class  1                  38.7                 7.7
                    2                  38.4                 7.1
                    3                  33.2                 7.6
                    4                  38.4                 7.5
                    5                  31.8                 6.1
LCA_Group_AG_class  1                  35.3                 8.8
                    2                  39.0                 7.2
                    3                  38.0                 5.5
                    4                  38.7                 8.2
                    5                  31.4                 5.6
LCA_Group_AGF_class 1                  30.8                 9.1
                    2                  40.4                 7.5
                    3                  31.9                 6.4
                    4                  37.9                 6.2
                    5                  56.9                 4.1

                       Context_HeartBreak  Context_CloseDeath  \
Column
LCA_Group_AF_class  1                12.6                 2.7
                    2                15.4                 2.4
                    3                12.7                 2.5
                    4                12.9                 2.7
                    5                12.6                 2.3
LCA_Group_AG_class  1                13.2                 2.6
                    2                13.5                 2.7
                    3                12.8                 2.2
                    4                13.5                 2.5
                    5                14.5                 2.7
LCA_Group_AGF_class 1                14.1                 2.6
                    2                12.2                 2.8
                    3                13.8                 2.7
                    4                14.1                 2.3
                    5                12.3                 1.8

                       Context_Finances  Context_Crime  Context_Disability
Column
LCA_Group_AF_class  1               6.7            0.6                 0.6
                    2               5.2            0.7                 0.5
                    3               6.0            0.6                 0.6
                    4               6.2            0.7                 0.6
                    5               6.7            1.2                 0.3
LCA_Group_AG_class  1               5.9            0.7                 0.5
                    2               5.7            0.6                 0.6
                    3               6.5            0.8                 0.4
                    4               6.5            0.7                 0.6
                    5               7.0            0.7                 0.6
LCA_Group_AGF_class 1               6.2            0.8                 0.6
                    2               6.1            0.5                 0.7
                    3               7.2            0.8                 0.5
                    4               6.1            1.0                 0.5
                    5               4.0            0.4                 0.3

[15 rows x 64 columns]

In [39]:
write_excel(
    file_path=RESULTS_DIR / "lca_class_exploration.xlsx",
    data=percentage_feature_result,
    sheet_name="percentage_feature_result",
    mode="a",
    index=True,
)

# Class Count Years

In [40]:
# Apply the function
count_years_result = aggregate_count(
    df,
    group_columns=class_columns,
    value_columns=["DateY"],
)
count_years_result = count_years_result.sort_index()
count_years_result

                       2013  2014  2015  2016  2017  2018  2019  2020  2021  \
Column
LCA_Group_AF_class  1  2916  3700  3527  3466  3783  3714  3993  4001  4677
                    2  1908  2330  2402  2348  2698  2807  2964  3021  3572
                    3  1346  1712  1866  1897  2170  2089  2248  2230  2509
                    4   926  1084  1126  1075  1382  1458  1609  1644  1779
                    5   816  1014   950   971  1097  1092  1133  1110  1238
LCA_Group_AGF_class 1  2736  3280  3361  3278  3634  3745  4048  3950  4581
                    2  2092  2535  2459  2449  2822  2801  3036  3074  3632
                    3  1468  1830  1911  1861  2115  2041  2177  2216  2409
                    4   885  1269  1163  1193  1484  1426  1531  1553  1819
                    5   731   926   977   976  1075  1147  1155  1213  1334
LCA_Group_AG_class  1  2680  3278  3367  3254  3599  3659  3872  3865  4370
                    2  1753  2222  2211  2216  2742  2703  2956  3067  3694
                    3  1619  2080  2046  2047  2256  2302  2438  2378  2760
                    4  1331  1590  1452  1537  1539  1513  1627  1666  1777
                    5   529   670   795   703   994   983  1054  1030  1174

                       2022  2023
Column
LCA_Group_AF_class  1  4875  5201
                    2  3881  3983
                    3  2499  2609
                    4  1922  2014
                    5  1333  1319
LCA_Group_AGF_class 1  4780  5237
                    2  4002  4257
                    3  2516  2337
                    4  1837  1897
                    5  1375  1398
LCA_Group_AG_class  1  4445  4506
                    2  3929  4174
                    3  2919  3180
                    4  2046  2046
                    5  1171  1220

In [41]:
write_excel(
    file_path=RESULTS_DIR / "lca_class_exploration.xlsx",
    data=count_years_result,
    sheet_name="count_years_result",
    mode="a",
    index=True,
)

In [42]:
# Calculate total sum for each group (index 'Column') and year (columns in count_years_result)
group_year_totals = count_years_result.groupby("Column").transform("sum")

# Divide each value by the corresponding group-year total to calculate percentages
percentage_years_result = count_years_result.div(group_year_totals) * 100
percentage_years_result = percentage_years_result.round(1)  # Round to 1 decimal place

percentage_years_result

                       2013  2014  2015  2016  2017  2018  2019  2020  2021  \
Column
LCA_Group_AF_class  1  36.9  37.6  35.7  35.5  34.0  33.3  33.4  33.3  34.0
                    2  24.1  23.7  24.3  24.1  24.2  25.2  24.8  25.2  25.9
                    3  17.0  17.4  18.9  19.4  19.5  18.7  18.8  18.6  18.2
                    4  11.7  11.0  11.4  11.0  12.4  13.1  13.5  13.7  12.9
                    5  10.3  10.3   9.6  10.0   9.9   9.8   9.5   9.2   9.0
LCA_Group_AGF_class 1  34.6  33.3  34.0  33.6  32.7  33.6  33.9  32.9  33.3
                    2  26.4  25.8  24.9  25.1  25.4  25.1  25.4  25.6  26.4
                    3  18.6  18.6  19.4  19.1  19.0  18.3  18.2  18.5  17.5
                    4  11.2  12.9  11.8  12.2  13.3  12.8  12.8  12.9  13.2
                    5   9.2   9.4   9.9  10.0   9.7  10.3   9.7  10.1   9.7
LCA_Group_AG_class  1  33.9  33.3  34.1  33.4  32.3  32.8  32.4  32.2  31.7
                    2  22.2  22.6  22.4  22.7  24.6  24.2  24.7  25.5  26.8
                    3  20.5  21.1  20.7  21.0  20.3  20.6  20.4  19.8  20.0
                    4  16.8  16.2  14.7  15.8  13.8  13.6  13.6  13.9  12.9
                    5   6.7   6.8   8.1   7.2   8.9   8.8   8.8   8.6   8.5

                       2022  2023
Column
LCA_Group_AF_class  1  33.6  34.4
                    2  26.7  26.3
                    3  17.2  17.2
                    4  13.2  13.3
                    5   9.2   8.7
LCA_Group_AGF_class 1  32.9  34.6
                    2  27.6  28.1
                    3  17.3  15.5
                    4  12.7  12.5
                    5   9.5   9.2
LCA_Group_AG_class  1  30.6  29.8
                    2  27.1  27.6
                    3  20.1  21.0
                    4  14.1  13.5
                    5   8.1   8.1

In [43]:
write_excel(
    file_path=RESULTS_DIR / "lca_class_exploration.xlsx",
    data=percentage_years_result,
    sheet_name="percentage_years_result",
    mode="a",
    index=True,
)