In [8]:
"""
Data exploration notebook for viewing missing values in suicide study dataset.
"""
import sys
from pathlib import Path
from dotenv import dotenv_values
import pandas as pd

# Load environment variables from the .env file
env_vars = dotenv_values()  # Load variables from the .env file

# Get the workspace path from the environment variables
WORKSPACE_PATH = Path(
    env_vars.get("WORKSPACE_PATH", "")
)  # Fetch WORKSPACE_PATH from .env

if not WORKSPACE_PATH:
    raise ValueError("WORKSPACE_PATH is not defined in the .env file or is empty.")

# Add the WORKSPACE_PATH folder to the Python path
sys.path.append(str(WORKSPACE_PATH))

# Import custom utility functions
from src.config.utils import read_csv, write_excel

DATA_DIR = Path(env_vars["DATA_DIR"])
RESULTS_DIR = Path(env_vars["RESULTS_DIR"])

In [9]:
def analyze_dataframe_columns(dataframe):
    """
    Analyzes DataFrame columns by calculating missing data statistics and unique value counts.

    Args:
        dataframe (pd.DataFrame): Input DataFrame for analysis.

    Returns:
        pd.DataFrame: Analysis results with columns:
            - column_name: Name of each column
            - missing_values_total: Count of missing values
            - missing_values_percent: Percentage of missing values
            - unique_values_count: Count of unique values
            - unique_value_counts: String of unique values and their counts
    """
    results = []

    for col in dataframe.columns:
        missing_total = dataframe[col].isnull().sum()
        missing_percent = 100 * missing_total / len(dataframe)

        unique_count = dataframe[col].nunique()
        value_counts = dataframe[col].value_counts().to_dict()
        value_counts_str = ", ".join([f"{k}: {v}" for k, v in value_counts.items()])

        results.append(
            [col, missing_total, missing_percent, unique_count, value_counts_str]
        )

    analysis_df = pd.DataFrame(
        results,
        columns=[
            "column_name",
            "missing_values_total",
            "missing_values_percent",
            "unique_values_count",
            "unique_value_counts",
        ],
    )

    # Sort the DataFrame by missing_values_total in descending order
    analysis_df = analysis_df.sort_values(by="missing_values_total", ascending=True)

    return analysis_df


def nan_exploration_in_rows(dataframe):
    """
    Analyzes NaN distribution across DataFrame rows.

    Args:
        dataframe (pd.DataFrame): Input DataFrame for analysis.

    Returns:
        pd.DataFrame: Analysis results with columns:
            - NaN_count: Number of NaN values in each row
            - Total: Count of rows with that NaN count
            - Percent: Percentage of rows with that NaN count
    """
    nan_counts = dataframe.isna().sum(axis=1).value_counts()
    full_index = list(range(0, len(dataframe.columns) + 1))
    nan_counts = nan_counts.reindex(full_index, fill_value=0)
    nan_counts = nan_counts.sort_index()
    nan_counts_percent = (nan_counts / len(dataframe)) * 100

    missing_data_rows = pd.concat(
        [
            pd.Series(full_index, name="NaN_count"),
            nan_counts.rename("Total"),
            nan_counts_percent.rename("Percent"),
        ],
        axis=1,
    )

    return missing_data_rows

In [10]:
# Data import
csv_file_path = DATA_DIR / "processed" / "mapped_data.csv"
df_raw = read_csv(csv_file_path)

In [11]:
# Split data and context
context_columns = [col for col in df_raw.columns if col.startswith("Context_")]
df_data = df_raw.drop(columns=context_columns, inplace=False)

In [12]:
# Data exploration
nan_columns_df = analyze_dataframe_columns(df_data)
nan_columns_df

,column_name,missing_values_total,missing_values_percent,unique_values_count,unique_value_counts
0,ID,0,0.000000,128330,"138421942: 1, 126297358,00: 1, 126300391,00: 1..."
1,Date,1,0.000779,29699,"2021-05-01: 1311, 2021-06-01: 1241, 2021-04-01..."
12,DateY,1,0.000779,11,"2023.0: 15133, 2022.0: 14517, 2021.0: 13793, 2..."
13,DateM,1,0.000779,12,"5.0: 11632, 6.0: 11550, 7.0: 11398, 8.0: 11100..."
3,Gender,7,0.005455,2,"M: 93811, F: 34512"
8,Fatal,71,0.055326,2,"0.0: 68489, 1.0: 59770"
10,Method,71,0.055326,11,"Hanging: 64233, Drugs: 21404, SelfHarm: 18453,..."
9,Place,107,0.083379,12,"House: 79745, Other: 13810, UtilitySpaces: 116..."
2,AgeGroup,1296,1.009896,16,"19_24: 13764, 30_34: 13377, 35_39: 13287, 25_2..."
4,Marital,16270,12.678251,7,"Single: 50741, Married: 40423, Divorced: 8782,..."
7,Income,55696,43.400608,4,"Steady: 25747, Dependent: 18228, Benefits: 167..."
6,WorkInfo,62969,49.068028,4,"Employed: 26495, Unemployed: 24645, Student: 1..."
11,Substance,65004,50.653783,4,"Alco: 36582, Sober: 16240, OtherSub: 8814, Alc..."
5,Education,88152,68.691654,6,"Primary: 12428, Secondary: 12240, Vocational: ..."
14,AbuseInfo,101643,79.204395,3,"Alco: 25035, OtherSub: 1278, AlcoOtherSub: 374"

In [13]:
write_excel(
    file_path=RESULTS_DIR / "nan_exploration.xlsx",
    data=nan_columns_df,
    sheet_name="nan_columns",
    mode="w",
    index=False,
)

In [14]:
nan_rows_df = nan_exploration_in_rows(df_data)
nan_rows_df

    NaN_count  Total    Percent
0           0   5558   4.331022
1           1  21217  16.533157
2           2  24896  19.399984
3           3  22917  17.857866
4           4  24964  19.452973
5           5  21630  16.854983
6           6   6725   5.240396
7           7    345   0.268838
8           8      9   0.007013
9           9      8   0.006234
10         10     60   0.046754
11         11      0   0.000000
12         12      0   0.000000
13         13      0   0.000000
14         14      1   0.000779
15         15      0   0.000000

In [17]:
write_excel(
    file_path=RESULTS_DIR / "nan_exploration.xlsx",
    data=nan_rows_df,
    sheet_name="nan_rows",
    mode="a",
    index=False,
)